import 'dart:convert';
import 'package:equatable/equatable.dart';

/// Hardware sensor types supported by SmartPark AI
enum SensorType {
  ioTParkingSensor,
  cctvCamera,
  anprCamera,
  rfidReader,
  barrierGate,
  ultrasonicSensor,
  magneticSensor,
  liDARSensor,
}

/// Telemetry event types generated by smart sensors
enum SensorEventType {
  vehicleEntry,
  vehicleExit,
  slotOccupied,
  slotVacated,
  sensorFailure,
  cameraOffline,
  barrierClosed,
  rfidDetection,
  anprDetection,
}

/// Comprehensive hardware sensor event model
class SensorDataModel extends Equatable {
  final String sensorId;
  final String parkingId;
  final String slotId;
  final SensorType sensorType;
  final SensorEventType eventType;
  final String detectedLicensePlate;
  final double confidenceScore;
  final bool isOnline;
  final Map<String, dynamic> telemetryPayload;
  final DateTime timestamp;

  const SensorDataModel({
    required this.sensorId,
    required this.parkingId,
    required this.slotId,
    required this.sensorType,
    required this.eventType,
    required this.detectedLicensePlate,
    required this.confidenceScore,
    required this.isOnline,
    required this.telemetryPayload,
    required this.timestamp,
  });

  SensorDataModel copyWith({
    String? sensorId,
    String? parkingId,
    String? slotId,
    SensorType? sensorType,
    SensorEventType? eventType,
    String? detectedLicensePlate,
    double? confidenceScore,
    bool? isOnline,
    Map<String, dynamic>? telemetryPayload,
    DateTime? timestamp,
  }) {
    return SensorDataModel(
      sensorId: sensorId ?? this.sensorId,
      parkingId: parkingId ?? this.parkingId,
      slotId: slotId ?? this.slotId,
      sensorType: sensorType ?? this.sensorType,
      eventType: eventType ?? this.eventType,
      detectedLicensePlate: detectedLicensePlate ?? this.detectedLicensePlate,
      confidenceScore: confidenceScore ?? this.confidenceScore,
      isOnline: isOnline ?? this.isOnline,
      telemetryPayload: telemetryPayload ?? this.telemetryPayload,
      timestamp: timestamp ?? this.timestamp,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'sensorId': sensorId,
      'parkingId': parkingId,
      'slotId': slotId,
      'sensorType': sensorType.name,
      'eventType': eventType.name,
      'detectedLicensePlate': detectedLicensePlate,
      'confidenceScore': confidenceScore,
      'isOnline': isOnline,
      'telemetryPayload': telemetryPayload,
      'timestamp': timestamp.toIso8601String(),
    };
  }

  factory SensorDataModel.fromMap(Map<String, dynamic> map, String id) {
    return SensorDataModel(
      sensorId: id,
      parkingId: map['parkingId'] ?? '',
      slotId: map['slotId'] ?? '',
      sensorType: SensorType.values.firstWhere(
        (e) => e.name == map['sensorType'],
        orElse: () => SensorType.ioTParkingSensor,
      ),
      eventType: SensorEventType.values.firstWhere(
        (e) => e.name == map['eventType'],
        orElse: () => SensorEventType.slotOccupied,
      ),
      detectedLicensePlate: map['detectedLicensePlate'] ?? '',
      confidenceScore: (map['confidenceScore'] ?? 98.0).toDouble(),
      isOnline: map['isOnline'] ?? true,
      telemetryPayload: Map<String, dynamic>.from(map['telemetryPayload'] ?? {}),
      timestamp: DateTime.tryParse(map['timestamp'] ?? '') ?? DateTime.now(),
    );
  }

  String toJson() => json.encode(toMap());

  factory SensorDataModel.fromJson(String source, String id) =>
      SensorDataModel.fromMap(json.decode(source), id);

  @override
  List<Object?> get props => [
        sensorId,
        parkingId,
        slotId,
        sensorType,
        eventType,
        detectedLicensePlate,
        confidenceScore,
        isOnline,
        telemetryPayload,
        timestamp,
      ];
}
