// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4z9VXz8pNzb8BKvxdnyIDbDsu6YgsP10',
    appId: '1:538147845713:web:43f3a1c13ff2d166eeaa70',
    messagingSenderId: '538147845713',
    projectId: 'smartpark-ai-c4608',
    authDomain: 'smartpark-ai-c4608.firebaseapp.com',
    storageBucket: 'smartpark-ai-c4608.firebasestorage.app',
    measurementId: 'G-T5GDE0BSJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ0DksSPMTlw8yRPtNiIPPnITveAgf1kk',
    appId: '1:538147845713:android:4f0970f5685329dceeaa70',
    messagingSenderId: '538147845713',
    projectId: 'smartpark-ai-c4608',
    storageBucket: 'smartpark-ai-c4608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzpj5q2YoCVBaAfdZxFpxWdEQC71IE52c',
    appId: '1:538147845713:ios:b3af5932d57cba8deeaa70',
    messagingSenderId: '538147845713',
    projectId: 'smartpark-ai-c4608',
    storageBucket: 'smartpark-ai-c4608.firebasestorage.app',
    iosBundleId: 'com.example.smartparkAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzpj5q2YoCVBaAfdZxFpxWdEQC71IE52c',
    appId: '1:538147845713:ios:b3af5932d57cba8deeaa70',
    messagingSenderId: '538147845713',
    projectId: 'smartpark-ai-c4608',
    storageBucket: 'smartpark-ai-c4608.firebasestorage.app',
    iosBundleId: 'com.example.smartparkAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4z9VXz8pNzb8BKvxdnyIDbDsu6YgsP10',
    appId: '1:538147845713:web:9a3cbc1c87963c55eeaa70',
    messagingSenderId: '538147845713',
    projectId: 'smartpark-ai-c4608',
    authDomain: 'smartpark-ai-c4608.firebaseapp.com',
    storageBucket: 'smartpark-ai-c4608.firebasestorage.app',
    measurementId: 'G-QM8YE9ZPHC',
  );
}
